import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Dead Man's Console",
    description: "Generated by create next app",
};

const ConsoleLayout = ({ children }: { children: React.ReactNode }) => {
    return <main className='h-full'>{children}</main>;
};

export default ConsoleLayout;
